#%RAML 0.8
---
title: Items API
documentation:
    - title: Items REST API
      content: |
        Welcome to the Items API.
baseUri: http://{host}:{port}/{version}
version: api
mediaType: application/json
protocols: [HTTP]

/items:
    displayName: Collection of items
    head:
        description: Head request
        responses:
            200:
                description: Return headers
    get:
        description: Get all item
        responses:
            200:
                description: Returns a list of items
    post:
        description: Create a new item
        body:
            application/json:
                schema: !include items.json
                example: |
                    {
                        "id": "507f191e810c19729de860ea",
                        "name": "Banana",
                        "description": "Tasty"
                    }
        responses:
            201:
                description: Created item
                body:
                    application/json:
                        schema: !include items.json

    /{id}:
        uriParameters:
            id:
                displayName: Item id
                type: string
                example: 507f191e810c19729de860ea
        displayName: Collection-item
        head:
            description: Head request
            responses:
                200:
                    description: Return headers
        get:
            description: Get a particular item
            responses:
                200:
                    body:
                        application/json:
                            schema: !include items.json
        delete:
            description: Delete a particular item
            responses:
                200:
                    description: Deleted item
        patch:
            description: Update a particular item
            body:
                application/json:
                    example: { "name": "Tree" }
            responses:
                200:
                    body:
                        application/json:
                            schema: !include items.json
